### ISSUE TITLE
I have no idea how I should make this font work

### ISSUE THREAD

**Issue by cmbn12** [JWalkerMailly/Source-Github-Theme#2]
Console error:
[HTML] asset://garrysmod/html/menu.html#/:0: The resource asset://garrysmod/html/Mona-Sans.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

Can you please explain how I am supposed to install fonts on my computer?

![изображение](https://github.com/JWalkerMailly/Source-Github-Theme/assets/114869567/ffafb1aa-0236-4df3-89c6-191af355b701)

**Comment by JWalkerMailly** [comment]
Install all fonts in your Window's fonts folder.

**Comment by cmbn12** [comment]
> Install all fonts in your Window's fonts folder.

Thanks. I have no idea where it is but hope Google helps me.

**Comment by cmbn12** [comment]
> Install all fonts in your Window's fonts folder.



https://github.com/JWalkerMailly/Source-Github-Theme/assets/114869567/71b214da-8dd5-4ea6-a38d-c76a27084eec

I have to do it like this right?

**Comment by cmbn12** [comment]
Ok, I figured this out, thanks
